class Config:
    BASE_URL = "http://localhost:8000/"
    API_URL = f"{BASE_URL}"
    JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNmRmNDY2Mi1kNzJiLTQ3ZjQtODhjMi0wYzA0MGY3ODY1NmYiLCJleHAiOjE3ODMwNjQ5MzF9.dG7UXl0il4bFiLVcMAVC3R-mO_5PCZzB9fBh8EGmLcE"
    WISHLIST_ID = ""
    ITEM_ID = ""